### ISSUE TITLE
Release new version to Maven with support for new pingback ACL

### ISSUE THREAD

**Issue by johnou** [paymentwall/paymentwall-java#11]
Hi,

Would you kindly release a new version of paymentwall-java to Maven with [support](https://github.com/paymentwall/paymentwall-java/commit/0173332dee80fa79a79f45e68892bb860098df87) for the [newly documented](https://docs.paymentwall.com/reference/pingback-home) address range?

Cheers!

**Comment by johnou** [comment]
Should be part of 2.0.4 thanks!

**Comment by liufanhhh** [comment]
已收到您的来信，我会尽快回复，谢谢！
